# Generated by Django 4.0.3 on 2022-06-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addrapt',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.CharField(blank=True, max_length=50, null=True)),
                ('apt', models.CharField(blank=True, max_length=50, null=True)),
                ('dong', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'addrapt',
                'managed': False,
            },
        ),
    ]
